apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}-pgbouncer
  labels:
    app: {{ include "pgbouncer.labels.app" . }}
    component: pgbouncer
    chart: {{ include "pgbouncer.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pgbouncer.ini: {{ include "pgbouncer.pgbouncer.pgbouncer.ini" . | b64enc | quote }}
  userlist.txt: {{ include "pgbouncer.pgbouncer.userlist.txt" . | b64enc | quote }}
  postgres-password: {{ .Values.auth.POSTGRESQL_PASSWORD | b64enc | quote }}